name: Discord Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Instalar dependências
        run: |
          pip install discord.py

      - name: Iniciar bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          python bot.py
